version: '3.8'
services:
  backend:
    container_name: backend-spring
    build: .
    ports:
      - "8080:8080"
    environment:
      PARAM: GITACTION
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped
